//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTestDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class issuer
    {
        public issuer()
        {
            this.EncCells = new HashSet<EncCell>();
        }
    
        public int C_Id { get; set; }
        public string C_Issuer { get; set; }
        public string C_IssuerShortName { get; set; }
        public bool C_Active { get; set; }
    
        public virtual ICollection<EncCell> EncCells { get; set; }
    }
}
